version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "8080:8000"
        - "9000:9000"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://host.docker.internal:8003"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ApiSettings:CatalogUrl=http://host.docker.internal:8000"
      - "ApiSettings:BasketUrl=http://host.docker.internal:8001"
      - "ApiSettings:OrderingUrl=http://host.docker.internal:8004"
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
    ports:
      - "8010:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ApiSettings:CatalogUrl=http://host.docker.internal:8000"
      - "ApiSettings:BasketUrl=http://host.docker.internal:8001"
      - "ApiSettings:OrderingUrl=http://host.docker.internal:8004"
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8005:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ApiSettings:GatewayAddress=http://host.docker.internal:8010"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8006:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  aspnetrunbasicblazor:
    container_name: aspnetrunbasicblazor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ApiSettings:GatewayAddress=http://host.docker.internal:8010"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8007:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
      - HealthChecksUI__HealthChecks__0__Uri=http://host.docker.internal:8000/hc
      - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
      - HealthChecksUI__HealthChecks__1__Uri=http://host.docker.internal:8001/hc
      - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
      - HealthChecksUI__HealthChecks__2__Uri=http://host.docker.internal:8002/hc
      - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
      - HealthChecksUI__HealthChecks__3__Uri=http://host.docker.internal:8004/hc
      - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
      - HealthChecksUI__HealthChecks__4__Uri=http://host.docker.internal:8005/hc
      - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
      - HealthChecksUI__HealthChecks__5__Uri=http://host.docker.internal:8006/hc
      - HealthChecksUI__HealthChecks__6__Name=AspnetRunBasics Blazor Health Check
      - HealthChecksUI__HealthChecks__6__Uri=http://host.docker.internal:8007/hc
      - HealthChecksUI__HealthChecks__7__Name=OcelotAPIGw Check
      - HealthChecksUI__HealthChecks__7__Uri=http://host.docker.internal:8010/hc
    ports:
      - "8008:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"